spring:
  application:
    name: mobile-operator-tariff-management

  datasource:
    url: jdbc:postgresql://localhost:5432/mobile_operator_db
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update # For a student project, let Hibernate generate/update the schema
    show-sql: true
    properties:
      hibernate:
        format_sql: true

server:
  port: 8080



